const data = {
  defaultPointsDisplayed: [
	"ME",
"Espace Fauriel",
"Mines Saint-Etienne",
"CIS/Hôpital Nord",
"Explora et Musée de la Mine",
"Gare de Chateaucreux",
"La cité du design",
  ],
  lines: [{
      start: "Mines Saint-Etienne",
      end: "ME",
      difficulty: 1,
      displayMin: true,
time : 5,
      times: { hard: 6, easy: 4 },
      align: "top",
    },
    {
      start: "Mines Saint-Etienne",
      end: "Espace Fauriel",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Opéra",
      end: "Espace Fauriel",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
{
      start: "Espace Fauriel",
      end: "Musée d'Art et d'Industrie",
      difficulty: 1,
      displayMin: true,
      time: 8,
      times: { hard: 9, easy: 7 },
      align: "top",
    },
{
      start: "Espace Fauriel",
      end: "Gare de Chateaucreux",
      difficulty: 1,
      displayMin: true,
      time: 10,
      times: { hard: 13, easy: 8 },
      align: "top",
    },
{
      start: "Opéra",
      end: "Musée d'Art et d'Industrie",
      difficulty: -1,
      displayMin: true,
      time: 8,
      times: { hard: 9, easy: 7 },
      align: "top",
    },
{
      start: "Opéra",
      end: "Gare de Chateaucreux",
      difficulty: -1,
      displayMin: true,
      time: 8,
      times: { hard: 11, easy: 6 },
      align: "top",
    },
    {
      start: "Gare de Chateaucreux",
      end: "Place du Peuple",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
{
      start: "Opéra",
      end: "Place du Peuple",
      difficulty: 1,
      displayMin: true,
      time: 8,
      times: { hard: 10, easy: 5 },
      align: "top",
    },
{
      start: "Musée d'Art et d'Industrie",
      end: "Place du Peuple",
      difficulty: -1,
      displayMin: true,
      time: 4,
      times: { hard: 5, easy: 2 },
      align: "top",
    },
{
      start: "Explora et Musée de la Mine",
      end: "Place du Peuple",
      difficulty: 1,
      displayMin: true,
      time: 7,
      times: { hard: 8, easy: 6 },
      align: "top",
    },
    {
      start: "Place Jean Jaurès",
      end: "Place du Peuple",
      difficulty: 0,
      displayMin: true,
      time: 2,
      align: "top",
    },
{
      start: "Cimetière du Crêt de Roc",
      end: "Place du Peuple",
      difficulty: -1,
      displayMin: true,
      time: 7,
      times: { hard: 9, easy: 6 },
      align: "top",
    },
{
      start: "Explora et Musée de la Mine",
      end: "Musée d'Art et d'Industrie",
      difficulty: -1,
      displayMin: true,
      time: 7,
      times: { hard: 8, easy: 6 },
      align: "top",
    },
    {
      start: "Place Jean Jaurès",
      end: "La cité du design",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
{
      start: "La cité du design",
      end: "Parc de Montaud",
      difficulty: 1,
      displayMin: true,
      time: 14,
      times: { hard: 8, easy: 20 },
      align: "top",
    },
{
      start: "La cité du design",
      end: "Cimetière du Crêt de Roc",
      difficulty: 1,
      displayMin: true,
      time: 8,
      times: { hard: 10, easy: 6 },
      align: "top",
    },
    {
      start: "Parc François Mitterand",
      end: "La cité du design",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Zénith",
      end: "La cité du design",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Stade Geoffroy Guichard",
      end: "La cité du design",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
{
      start: "La cité du design",
      end: "Musée Art Moderne",
      difficulty: -1,
      displayMin: true,
      time: 11,
      times: { hard: 12, easy: 9 },
      align: "top",
    },
{
      start: "Parc de Montaud",
      end: "CIS/Hôpital Nord",
      difficulty: 1,
      displayMin: true,
      time: 20,
      times: { hard: 25, easy: 14 },
      align: "top",
    },
{
      start: "Musée Art Moderne",
      end: "CIS/Hôpital Nord",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Parc de Montaud",
      end: "Explora et Musée de la Mine",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
{
      start: "Parc de Montaud",
      end: "Place Jean Jaurès",
      difficulty: -1,
      displayMin: true,
      time: 12,
      times: { hard: 15, easy: 9 },
      align: "top",
    },
{
      start: "Explora et Musée de la Mine",
      end: "Place Jean Jaurès",
      difficulty: 1,
      displayMin: true,
      time: 5,
      times: { hard: 6, easy: 4 },
      align: "top",
    },
{
      start: "Cimetière du Crêt de Roc",
      end: "Place Jean Jaurès",
      difficulty: -1,
      displayMin: true,
      time: 7,
      times: { hard: 9, easy: 6 },
      align: "top",
    },
{
      start: "Parc des Sports de Méons",
      end: "CIS/Hôpital Nord",
      difficulty: 1,
      displayMin: true,
      time: 22,
      times: { hard: 25, easy: 19 },
      align: "top",
    },
{
      start: "Parc des Sports de Méons",
      end: "Stade Geoffroy Guichard",
      difficulty: 0,
      displayMin: true,
      time: 11,
      align: "top",
    },
{
      start: "Parc des Sports de Méons",
      end: "Musée Art Moderne",
      difficulty: 1,
      displayMin: true,
      time: 18,
      times: { hard: 20, easy: 16 },
      align: "top",
    },
{
      start: "Parc des Sports de Méons",
      end: "Zénith",
      difficulty: 0,
      displayMin: true,
      time: 10,
      align: "top",
    },
{
      start: "Parc des Sports de Méons",
      end: "Parc François Mitterand",
      difficulty: 0,
      displayMin: true,
      time: 13,
      align: "top",
    },
{
      start: "Zénith",
      end: "Parc François Mitterand",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
{
      start: "Stade Geoffroy Guichard",
      end: "Zénith",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
{
      start: "Stade Geoffroy Guichard",
      end: "Musée Art Moderne",
      difficulty: 1,
      displayMin: true,
      time: 10,
      times: { hard: 12, easy: 8},
      align: "top",
    },
{
      start: "Parc François Mitterand",
      end: "Gare de Chateaucreux",
      difficulty: 1,
      displayMin: true,
      time: 5,
      times: { hard: 6, easy: 4 },
      align: "top",
    },
{
      start: "Cimetière du Crêt de Roc",
      end: "Gare de Chateaucreux",
      difficulty: 1,
      displayMin: true,
      time: 8,
      times: { hard: 11, easy: 6 },
      align: "top",
    },
{
      start: "Cimetière du Crêt de Roc",
      end: "Parc François Mitterand",
      difficulty: 1,
      displayMin: true,
      time: 9,
      times: { hard: 12, easy: 7 },
      align: "top",
    },
{
      start: "Parc des Sports de Méons",
      end: "Gare de Chateaucreux",
      difficulty: 0,
      displayMin: true,
      time: 14,
      align: "top",
    },
{
      start: "Parc de Montaud",
      end: "Musée Art Moderne",
      difficulty: 1,
      displayMin: true,
      time: 14,
      times: { hard: 16, easy: 12 },
      align: "top",
    },
  ],
  points: {
    "ME": { x: 943, y: 1162 },
    "Mines Saint-Etienne": { x: 880, y:1069  },
    "Espace Fauriel": { x: 831, y:973},
"CIS/Hôpital Nord": {x : 390,y: 63},
"Explora et Musée de la Mine": {x: 507,y: 834},
"Stade Geoffroy Guichard": {x :664,y: 424},
"Parc de Montaud": {x: 475,y: 610},
"Parc des Sports de Méons": {x: 918,y: 475},
"Musée d'Art et d'Industrie": {x: 637,y: 910},
"Opéra": {x: 756,y: 868},
"Zénith": {x: 696,y: 519},
"La cité du design": {x: 592,y: 580},
"Parc François Mitterand": {x: 699,y: 600},
"Gare de Chateaucreux": {x: 808,y: 703},
"Place du Peuple": {x: 642,y: 825},
"Place Jean Jaurès": {x: 618,y:747 },
"Cimetière du Crêt de Roc": {x: 693,y: 715},
"Musée Art Moderne": {x: 480,y: 265},

  },
};